### ISSUE TITLE
Plug-In not appearing in Protege

### ISSUE THREAD

**Issue by Prata129** [TomasMolinaGallego/Protege-OQuaRE-plugin#2]
Hi, I was trying to use your plug-in however I can't see it in my Protege, I tried we the files you provided and even created the jar file with maven and after adding the Jar files to the plugins directory I still can't see it. Is there any omitted step I might have skipped?

**Comment by TomasMolinaGallego** [comment]
The plug-in was designed for Protégé 5.5, with others versions it may have unknow behavieur. You have to put the two jars in the "plugin" folder of the root directory of Protégé instalation. Once the jars added, on the tab "Window" -> "Views" -> "Ontology views" it should appear "OQuaRE metrics and score" to select if it doesn't I don't know what the problem could be.
